<a href="https://colab.research.google.com/github/varunsboy17/Credit-Card-Fraud-Analysis-Prediction-using-AutoML/blob/master/CreditCardFraud_with_H2OML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import pandas as pd

!pip install h2o
import h2o

Requirement already satisfied: h2o in /usr/local/lib/python3.6/dist-packages (3.26.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from h2o) (2.21.0)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from h2o) (0.16.0)
Requirement already satisfied: colorama>=0.3.8 in /usr/local/lib/python3.6/dist-packages (from h2o) (0.4.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.6/dist-packages (from h2o) (0.8.3)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->h2o) (1.24.3)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->h2o) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->h2o) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->h2o) (3.0.4)

In [17]:
print(h2o.__version__)
from h2o.automl import H2OAutoML
h2o.init(max_mem_size = '16G')

3.26.0.4
Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ------------------------------------------------------------------
H2O cluster uptime:         27 mins 31 secs
H2O cluster timezone:       Etc/UTC
H2O data parsing timezone:  UTC
H2O cluster version:        3.26.0.4
H2O cluster version age:    1 day
H2O cluster name:           H2O_from_python_unknownUser_y8tcaq
H2O cluster total nodes:    1
H2O cluster free memory:    13.84 Gb
H2O cluster total cores:    2
H2O cluster allowed cores:  2
H2O cluster status:         locked, healthy
H2O connection url:         http://localhost:54321
H2O connection proxy:
H2O internal security:      False
H2O API Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python version:             3.6.8 final
--------------------------  ------------------------------------------------------------------

In [18]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [19]:
%%time
train_trns = h2o.import_file('/content/drive/My Drive/Credit Card Fraud Dataset/train_transaction.csv')
train_id = h2o.import_file('/content/drive/My Drive/Credit Card Fraud Dataset/train_identity.csv')
test_trns = h2o.import_file('/content/drive/My Drive/Credit Card Fraud Dataset/test_transaction.csv')
test_id = h2o.import_file('/content/drive/My Drive/Credit Card Fraud Dataset/test_identity.csv')

Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%
CPU times: user 1.23 s, sys: 147 ms, total: 1.38 s
Wall time: 1min 3s

In [0]:
all_train = train_trns.merge(train_id, all_x=True)
all_test = test_trns.merge(test_id, all_x=True)

In [0]:
x = all_train.drop('isFraud').columns
y = 'isFraud'
all_train[y] = all_train[y].asfactor()

In [30]:
aml = H2OAutoML(max_models=30, seed=45, max_runtime_secs=7200)
aml.train(x=x, y=y, training_frame=all_train)

AutoML progress: |████████████████████████████████████████████████████████| 100%

In [31]:
lb = aml.leaderboard
lb.head(rows=lb.nrows)

model_id,auc,logloss,mean_per_class_error,rmse,mse
XGBoost_1_AutoML_20190914_074629,0.825778,0.301448,0.287349,0.317855,0.101032

In [32]:
aml.leader

Model Details
=============
H2OXGBoostEstimator :  XGBoost
Model Key:  XGBoost_1_AutoML_20190914_074629


Model Summary:

     number_of_trees
0               92.0

ModelMetricsBinomial: xgboost
** Reported on train data. **

MSE: 0.01627403606714754
RMSE: 0.12756973021507703
LogLoss: 0.07260630984218717
Mean Per-Class Error: 0.13040002343787382
AUC: 0.9394105792978894
pr_auc: 0.7329075195310224
Gini: 0.8788211585957788

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.21922570363334987:

                 0        1   Error                 Rate
0      0  567281.0   2596.0  0.0046    (2596.0/569877.0)
1      1    8055.0  12608.0  0.3898     (8055.0/20663.0)
2  Total  575336.0  15204.0   0.018   (10651.0/590540.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold          value    idx
0                        max f1   0.219226       0.703042  198.0
1                        max f2   0.112715       0.683287  246.0
2                  max f0point5   0.352788       0.803792  161.0
3                  max accuracy   0.266908       0.982370  182.0
4                 max precision   0.985977       1.000000    0.0
5                    max recall   0.007161       1.000000  398.0
6               max specificity   0.985977       1.000000    0.0
7              max absolute_mcc   0.243468       0.704942  189.0
8    max min_per_class_accuracy   0.037209       0.862750  320.0
9   max mean_per_class_accuracy   0.051957       0.869600  301.0
10                      max tns   0.985977  569877.000000    0.0
11                      max fns   0.985977   20599.000000    0.0
12                      max fps   0.006914  569877.000000  399.0
13                      max tps   0.007161   20663.000000  398.0
14                      max tnr   0.985977       1.000000    0.0
15                      max fnr   0.985977       0.996903    0.0
16                      max fpr   0.006914       1.000000  399.0
17                      max tpr   0.007161       1.000000  398.0

Gains/Lift Table: Avg response rate:  3.50 %, avg score:  3.95 %

      group  ...         gain  cumulative_gain
0         1  ...  2747.312701      2747.312701
1         2  ...  2333.983768      2540.665733
2         3  ...  1083.638149      2054.962458
3         4  ...   443.520336      1652.136037
4         5  ...   245.084595      1370.744810
5         6  ...    55.737308       713.241059
6         7  ...   -17.243382       469.746245
7         8  ...   -43.377051       341.465421
8         9  ...   -61.961637       206.988217
9        10  ...   -74.543440       136.606495
10       11  ...   -80.351353        93.214925
11       12  ...   -86.129687        63.202777
12       13  ...   -90.857022        41.301567
13       14  ...   -94.655591        24.230422
14       15  ...   -95.670497        10.976679
15       16  ...   -98.790108         0.000000

[16 rows x 14 columns]

ModelMetricsBinomial: xgboost
** Reported on cross-validation data. **

MSE: 0.10103176892126976
RMSE: 0.31785494949940574
LogLoss: 0.3014478531207782
Mean Per-Class Error: 0.24961683256292355
AUC: 0.8257776527726588
pr_auc: 0.5135841910154494
Gini: 0.6515553055453176

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.48932373498130766:

                 0        1   Error                 Rate
0      0  568112.0   1765.0  0.0031    (1765.0/569877.0)
1      1   11811.0   8852.0  0.5716    (11811.0/20663.0)
2  Total  579923.0  10617.0   0.023   (13576.0/590540.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold          value    idx
0                        max f1   0.489324       0.565985  133.0
1                        max f2   0.479977       0.492856  139.0
2                  max f0point5   0.503875       0.719603  125.0
3                  max accuracy   0.501722       0.977439  126.0
4                 max precision   0.994518       1.000000    0.0
5                    max recall   0.001962       1.000000  398.0
6               max specificity   0.994518       1.000000    0.0
7              max absolute_mcc   0.495650       0.592179  129.0
8    max min_per_class_accuracy   0.475530       0.667231  147.0
9   max mean_per_class_accuracy   0.476769       0.750383  144.0
10                      max tns   0.994518  569877.000000    0.0
11                      max fns   0.994518   20624.000000    0.0
12                      max fps   0.001662  569877.000000  399.0
13                      max tps   0.001962   20663.000000  398.0
14                      max tnr   0.994518       1.000000    0.0
15                      max fnr   0.994518       0.998113    0.0
16                      max fpr   0.001662       1.000000  399.0
17                      max tpr   0.001962       1.000000  398.0

Gains/Lift Table: Avg response rate:  3.50 %, avg score: 21.14 %

      group  ...         gain  cumulative_gain
0         1  ...  2596.817418      2596.817418
1         2  ...  1626.512989      2110.231901
2         3  ...   250.939234      1446.826103
3         4  ...    94.476478       977.114504
4         5  ...   101.775350       924.274726
5         6  ...    16.987616       463.085793
6         7  ...   -48.766135       242.698210
7         8  ...   -69.254202       104.154715
8         9  ...   -75.536597        67.382825
9        10  ...   162.923728        84.416590
10       11  ...   -59.879979        60.367162
11       12  ...   -80.544935        40.236862
12       13  ...   -90.030489        23.953443
13       14  ...   -94.482892        10.793851
14       15  ...   -97.144655         0.000000

[15 rows x 14 columns]

Cross-Validation Metrics Summary:

                                    mean  ...   cv_4_valid   cv_5_valid
0                  accuracy   0.97637415  ...   0.97233886    0.9799675
1                       auc    0.8937671  ...    0.8229097   0.93894124
2                       err  0.023625834  ...  0.027661124  0.020032512
3                 err_count       2790.4  ...       3267.0       2366.0
4                  f0point5   0.66764843  ...   0.58992153    0.7343188
5                        f1   0.60306597  ...   0.48913214   0.68835616
6                        f2    0.5511858  ...   0.41775736   0.64780843
7            lift_top_group    27.073505  ...    25.980162    27.745564
8                   logloss   0.30144784  ...   0.64893764  0.071016684
9       max_per_class_error   0.47825804  ...   0.61927944   0.37666985
10                      mcc    0.6006446  ...    0.4977964   0.68209445
11  mean_per_class_accuracy   0.75729984  ...    0.6871892    0.8082108
12     mean_per_class_error   0.24270017  ...   0.31281078   0.19178922
13                      mse  0.101031765  ...   0.22791202  0.016699813
14                precision   0.72085726  ...    0.6838653    0.7685294
15                       r2   -1.9905583  ...   -5.7887616    0.5121748
16                   recall    0.5217419  ...   0.38072056    0.6233302
17                     rmse   0.26787975  ...   0.47740132   0.12922776
18              specificity    0.9928577  ...    0.9936579    0.9930914

[19 rows x 8 columns]

Scoring History:

                timestamp  ... training_lift  training_classification_error
0     2019-09-14 09:26:46  ...      1.000000                       0.965010
1     2019-09-14 09:28:05  ...     27.405083                       0.025451
2     2019-09-14 09:28:28  ...     27.587576                       0.024870
3     2019-09-14 09:28:54  ...     27.752105                       0.024246
4     2019-09-14 09:29:20  ...     27.863403                       0.023721
5     2019-09-14 09:29:45  ...     27.965024                       0.023082
6     2019-09-14 09:30:12  ...     28.076323                       0.022561
7     2019-09-14 09:30:40  ...     28.148909                       0.022068
8     2019-09-14 09:31:09  ...     28.206978                       0.022026
9     2019-09-14 09:31:38  ...     28.279564                       0.022088
10    2019-09-14 09:32:10  ...     28.298920                       0.021259
11    2019-09-14 09:32:40  ...     28.342472                       0.020530
12    2019-09-14 09:33:10  ...     28.381185                       0.020732
13    2019-09-14 09:33:43  ...     28.405380                       0.020026
14    2019-09-14 09:34:15  ...     28.429575                       0.019348
15    2019-09-14 09:34:49  ...     28.444093                       0.019045
16    2019-09-14 09:35:22  ...     28.444093                       0.018678
17    2019-09-14 09:35:57  ...     28.453771                       0.018480
18    2019-09-14 09:36:32  ...     28.473127                       0.018143
19    2019-09-14 09:37:02  ...     28.473127                       0.018036

[20 rows x 10 columns]

Variable Importances:

          variable  relative_importance  scaled_importance  percentage
0             V258         52436.750000           1.000000    0.100520
1               C1         24817.818359           0.473291    0.047575
2              C13         21560.853516           0.411178    0.041332
3              C14         21370.853516           0.407555    0.040968
4             V294         14610.700195           0.278635    0.028009
5             V201         13075.166016           0.249351    0.025065
6   TransactionAmt         11105.234375           0.211783    0.021289
7              C11          9712.950195           0.185232    0.018620
8    TransactionID          9595.095703           0.182984    0.018394
9               D2          8880.705078           0.169360    0.017024
10           card2          8492.297852           0.161953    0.016280
11           card1          8007.672852           0.152711    0.015351
12             D15          7714.756836           0.147125    0.014789
13             V70          7258.094727           0.138416    0.013914
14             C12          7063.938477           0.134714    0.013541
15            V189          6830.902832           0.130269    0.013095
16           addr1          6184.015625           0.117933    0.011855
17              D1          6104.833496           0.116423    0.011703
18              C8          5583.824707           0.106487    0.010704
19              C6          5373.672852           0.102479    0.010301

See the whole table with table.as_data_frame()

In [0]:
h2o.remove(train_trns)
h2o.remove(train_id)
h2o.remove(test_trns)
h2o.remove(test_id)
#test = h2o.import_file('/content/drive/My Drive/Credit Card Fraud Dataset/test_transaction.csv')

In [37]:
preds = aml.predict(all_test)
preds['p1'].as_data_frame().values.flatten().shape

xgboost prediction progress: |████████████████████████████████████████████| 100%

/usr/local/lib/python3.6/dist-packages/h2o/job.py:70: UserWarning: Test/Validation dataset column 'DeviceInfo' has levels not trained on: [2014819, 2PS64, 4009A, 4027A, 4047A, 4047G, 5010G, 5011A, 5012G, 5015A, 5025G, 5026A, 5026A Build/NRD90M, 5033A, 5041C, 5044T, 5049W, 5049Z, 5052Y, 5054S, 5056A, 5058A, 5059A, 5080A, 5080X, 5085A, 5085B, 5086A, 5099A, 5099A Build/O00623, 6016A, 6036A Build/JLS36C, 6043A, 6045O, 6062W, 7040N, 7048A, 7048X, 8050G, 8080, 8082, 8_Plus, 9003A, 9024W, A10, A10 Pro Build/LMY47I, A1_PRO, A37fw, A462C, A502DL, A50LT, A622GL, A7, AGS-L03, AGS-L09, AGS-W09, ALCATELONETOUCH, ALE-L02, ALE-L21, ALE-L23, ALP-L09, ALP-L29, ANE-LX1, ANE-LX1 Build/HUAWEIANE-LX1, ANE-LX2, ANE-LX3, ASUS_A002A, ASUS_A006, ASUS_A007, ASUS_A009, ASUS_X008DC, ASUS_X00AD, ASUS_X00HD, ASUS_X00LDA, ASUS_X00PD, ASUS_Z00XS, ASUS_Z012DC, ASUS_Z017DC, ASUS_Z01HD, ASUS_Z01MD, ATU-L11, ATU-L21, ATU-LX3, ATU-LX3 Build/HUAWEIATU-LX3, AUM-L29, AW790, AX681, AX921, Alcatel_5044R, Alcatel_5098O, Alcatel_6060C, Alpha 950, Alumini_3_Plus, Android 8.0.0, Aquaris_M4.5, Armor, Astro, Azumi_DOSHI_A55_QL, Azumi_IRO_A5_Q, B1-850, BAC-L03, BAH-L09, BAH-W09, BBB100-1 Build/OPM1.171019.026, BBF100-2, BGO-DL09, BKL-L09, BLA-A09, BLA-A09 Build/HUAWEIBLA-A09, BLA-AL00, BLA-L09, BLA-L29, BLA-L29 Build/HUAWEIBLA-L29S, BLADE, BLADE A520, BLADE A6 MAX Build/N2G47H, BLADE A602, BLADE L7, BLADE V8 SE, BLADE V8Q, BLADE V9, BLADE V9 Build/OPR1.170623.032, BLL-L22, BLL-L23, BLN-L21, BLN-L24, BND-L21, BND-L24, BV6000S, Blade L2 Plus, Blade V580, Blade V6, Blade V6 Plus, Bluboo, C2105, C5, C6506, C6506 Build/10.7.A.0.222, C6902, CAM-L03, CAM-L21, CHC-U03, CLT-L04, CLT-L04 Build/HUAWEICLT-L04, CLT-L29, CLT-L29 Build/HUAWEICLT-L29, CMR-AL09, CMR-W09, CMR-W19, COL-L29, CPH1725, CPH1835, CPH1835 Build/O11019, CPU, CRO-L03, CUBOT_X18_Plus, Che2-L23, D2206, D2303, D5303, D5503 Build/14.6.A.0.368, D5803, D6653, DIG-L03, DLI-L22, DRA-L21, DRA-LX3, DRA-LX3 Build/HUAWEIDRA-LX3, DUO, E2306, E5306 Build/27.1.A.1.81, E5306 Build/27.3.A.0.173, E5603, E5663, E6782, E6883, E6910, EML-L09, EML-L09 Build/HUAWEIEML-L09, EML-L29, ENERGY, EV05, EVA-L09, EVA-L19, Energy, F3111, F3112, F3116, F3216, F5121 Build/34.4.A.2.107, FIG-LX1, FIG-LX1 Build/HUAWEIFIG-LX1, FIG-LX3, FLA-LX3, FLA-LX3 Build/HUAWEIFLA-LX3, FP1U, FRD-L04, FRD-L09, FRD-L19, Fedora, FunWebProducts, G24027K, G3112, G3121, G3121 Build/48.1.A.2.21, G3123 Build/48.1.A.2.21, G3123 Build/48.1.A.2.50, G3223 Build/48.1.A.2.21, G3223 Build/48.1.A.2.50, G3311, G3312, G3313 Build/43.0.A.7.55, G3313 Build/43.0.A.7.70, G3412, G8141 Build/47.1.A.12.270, G8231, G8232, G8441, GHIA_AXIS7, GHIA_AXIS7P, GLAM, GT-I8190L, GT-I9060I, GT-I9060L, GT-I9060M, GT-I9195 Build/KOT49H, GT-I9300I, GT-I9301I, GT-I9505, GT-N5120, GT-N8013, GT-S6810M, Galaxy, Gini s5Pro Build/NRD90M, Gravity, H3123, H3223, H3223 Build/50.1.A.10.40, H3311, H8216, H8314, HK-914581, HMA-L09, HS20502-16, HTC 10, HTC 10 Build/OPR1.170623.027, HTC Desire 10 lifestyle, HTC Desire 530, HTC Desire 626s, HTC Desire 650, HTC One, HTC One A9s, HTC One M9PLUS, HTL23, HUAWEI CUN-L03, HUAWEI G7-L03, HUAWEI RIO-L03, HUAWEI TAG-L13, HUAWEI VNS-L23, HUAWEI VNS-L31, HUAWEI VNS-L53, HUAWEI Y560-L03, Hisense F20, Hisense F23, Hisense F24, Hisense F8 MINI, Hisense Hi 3 Build/NRD90M, Hisense L675, Hisense T963, Hisense U963, IM6, INE-LX2 Build/HUAWEIINE-LX2, INFINIT_1, Ilium L1120, Ilium M3 Build/NRD90M, Ilium X510, Ilium X520, Ilium X710, Infinit MX Build/NRD90M, Infinit_Lite_2, Infinit_X_CAM, Infinity, JKM-LX3, K011 Build/KOT49H, K014, K81, KEMPLER_TV, KFAPWI, KFARWI, KFASWI, KFAUWI, KFDOWI, KFFOWI, KFGIWI, KFKAWI, KFSUWI, KFTBWI, KFTHWI, KFTT, KYOCERA-C6742, KYOCERA-C6742A, L-03K, LAVA_R1, LDN-L21, LDN-LX3, LEX722, LG-D120 Build/KOT49I.V10a, LG-D280, LG-D325, LG-D415, LG-D631, LG-D690, LG-D805, LG-D852, LG-D852G, LG-G710, LG-H500, LG-H542, LG-H631MX, LG-H634, LG-H650, LG-H700, LG-H811, LG-H831, LG-H840, LG-H860, LG-H870, LG-H870DS, LG-H870DS Build/OPR1.170623.032, LG-H872, LG-H873, LG-H873 Build/NRD90U, LG-H910, LG-H918, LG-H930, LG-H931 Build/OPR1.170623.026, LG-H955, LG-H990, LG-K120, LG-K200, LG-K210, LG-K220, LG-K240, LG-K410, LG-K425, LG-K430, LG-K500, LG-K520, LG-K530, LG-K540, LG-K557 Build/MXB48T, LG-K580, LG-LS777, LG-LS993, LG-LS997, LG-LS997 Build/OPR1.170623.032, LG-M151, LG-M153, LG-M210, LG-M250, LG-M320, LG-M327, LG-M400, LG-M430, LG-M700, LG-M700 Build/OPM1.171019.026, LG-M703, LG-M710, LG-Q710AL, LG-TP260, LG-TP450, LG-UK495, LG-US998, LG-V400, LG-V410/V41020e, LG-V530, LG-X150, LG-X165g, LG-X180g, LG-X210, LG-X220, LG-X230, LG-X240, LGL157BL, LGL158VL, LGL164VL, LGL59BL, LGL82VL, LGL84VL, LGLS676, LGLS775, LGMP260, LGMP450, LGMS210, LGMS330, LGMS550, LGUS110, LLD-L21, LLD-L31, LLD-L31 Build/HONORLLD-L31, LM-G710, LM-G710VM, LM-Q610(FGN, LM-Q610.FG, LM-Q710(FGN, LM-Q710.FG, LM-Q710.FGN, LM-Q850, LM-V350, LM-V405, LM-X210, LM-X210 Build/N2G47H, LM-X210CM, LM-X212(G, LM-X410(FG, LM-X410.F, LM-X410PM, LML413DL, LYA-L09, Lenovo A2016b30, Lenovo K33b36, Lenovo P2a42, Lenovo PB2-650Y, Lenovo PB2-670Y, Lenovo TB-7104F Build/O11019, LenovoA3300-GV, Life, Lifesize, Lumia, M4 SS4453, M4 SS4456, M4 SS4457, M4 SS4458, M4 SS4458-R, M4_B2, M4_B3, M5, MB520, MHA-L09, MHA-L29, MI 4W Build/MMB29M, MI MAX 3, MIX, MIX Build/OPR1.170623.032, MXG401, MYA-L03, MYA-L13, Max10, Max10 Build/LMY47I, Mi A1, Mi A1 Build/OPM1.171019.026, Mi A2, Mi A2 Lite, Miracle, Moto C, Moto C Plus, Moto E (4), Moto E (4) Build/NDQ26.69-64-9, Moto E (4) Build/NMA26.42-157, Moto E (4) Build/NMA26.42-167, Moto E (4) Plus, Moto E (4) Plus Build/NMA26.42-162, Moto E (4) Plus Build/NMA26.42-167, Moto G (4), Moto G (4) Build/NPJS25.93-14-8.1-9, Moto G (4) Build/NPJS25.93-14.7-8, Moto G (5), Moto G (5) Build/NPPS25.137-93-12, Moto G (5) Build/NPPS25.137-93-14, Moto G (5) Build/OPP28.85-13, Moto G (5) Build/OPPS28.85-13-2, Moto G (5) Plus, Moto G (5) Plus Build/NPN25.137-35, Moto G (5) Plus Build/NPNS25.137-92-14, Moto G (5) Plus Build/NPNS25.137-93-14, Moto G (5) Plus Build/OPS28.85-13, Moto G (5) Plus Build/OPSS28.85-13-3, Moto G Play, Moto G Play Build/NPIS26.48-43-2, Moto X Play, Moto Z2 Play, Moto Z2 Play Build/NPSS26.118-19-22, Moto Z2 Play Build/OPS27.76-12-25, Moto Z2 Play Build/OPSS27.76-12-25-3, Moto Z2 Play Build/OPSS27.76-12-25-7, Moto Z3 Play, Moto Z3 Play Build/OPW28.70-22, MotoE2, MotoG3 Build/MPIS24.65-33.1-2-10, N1, N5702L, N9137, N9517, N9519, N9560, NATIVO Build/NRD90M, NEM-L51, NX16A11264, NX551J, NX591J, Neffos, Neffos X1 Max, Neffos_C7, Neffos_C9A, Nexus 5, Nexus 5X, Nexus 5X Build/N2G48C, Nexus 5X Build/OPM7.181005.003, Nexus 6P, Nokia, Nokia 2 Build/NMF26F, Nokia 6.1 Build/OPR1.170623.026, Nokia_X, Note8, ONEPLUS A3000, ONEPLUS A3003, ONEPLUS A3003 Build/OPR1.170623.032, ONEPLUS A3010, ONEPLUS A5000, ONEPLUS A5000 Build/OPM1.171019.011, ONEPLUS A5010, ONEPLUS A6003, ONEPLUS A6003 Build/PKQ1.180716.001, ONEPLUS A6013, ONIX, Orange_Rise_33, P002, P008, P00I, P10, P5047A, P5525A, P5526A, PAR-LX9, PIC-LX9, POCOPHONE, PRA-LX1, PRA-LX2, PRA-LX3, PSPC550, PSPCL20A0, PSPCM20A0, Phone, Pixel 2, Pixel 2 Build/OPM2.171026.006.C1, Pixel 2 Build/OPM2.171026.006.G1, Pixel 2 Build/PPR1.180610.009, Pixel 2 Build/PPR2.180905.005, Pixel 2 Build/PPR2.181005.003, Pixel 2 XL, Pixel 2 XL Build/OPM2.171026.006.H1, Pixel 2 XL Build/PPR2.180905.005, Pixel 2 XL Build/PPR2.181005.003, Pixel 3, Pixel 3 XL, Pixel Build/OPM4.171019.021.P1, Pixel XL, Pixel XL Build/OPM4.171019.021.P1, Pixel XL Build/PPR2.181005.003, Polaroid, Power_2, Q01A, Q05A, QMV7B, R505, R7plusf, R8006, RAINBOW, RCT6103W46, RCT6303W87M7, RCT6513W87, RCT6873W42M, RCT6873W42M_F7, RCT6973W43MD, RCT6B03W13, RIDGE, RIM, RNE-L03, RNE-L21, RNE-L22, RNE-L23, ROCKET, Redmi 4A, Redmi 4X, Redmi 5 Plus, Redmi 5 Plus Build/OPM1.171019.019, Redmi 5A Build/N2G47H, Redmi 6, Redmi 6A, Redmi Note 3, Redmi Note 3 Build/NMF26Q, Redmi Note 4, Redmi Note 5, Redmi Note 5 Build/OPM1.171019.011, Redmi Note 5A, Redmi Note 6 Pro, Redmi S2, Rex Build/MRA58K, S60, S60 Lite Build/NRD90M, S8, S9+, SAMSUNG SM-A320FL Build/R16NW, SAMSUNG SM-A520F Build/R16NW, SAMSUNG SM-A520W Build/NRD90M, SAMSUNG SM-A530F Build/NMF26X, SAMSUNG SM-A530F Build/R16NW, SAMSUNG SM-A605GN Build/R16NW, SAMSUNG SM-G390F Build/NRD90M, SAMSUNG SM-G532F Build/MMB29T, SAMSUNG SM-G610M Build/M1AJQ, SAMSUNG SM-G900M Build/MMB29M, SAMSUNG SM-G930A Build/R16NW, SAMSUNG SM-G930F Build/R16NW, SAMSUNG SM-G930P Build/R16NW, SAMSUNG SM-G930T Build/R16NW, SAMSUNG SM-G935A Build/R16NW, SAMSUNG SM-G935F Build/R16NW, SAMSUNG SM-G935T Build/R16NW, SAMSUNG SM-G960F Build/R16NW, SAMSUNG SM-G960U1 Build/R16NW, SAMSUNG SM-J330FN Build/NRD90M, SAMSUNG SM-J400M Build/R16NW, SAMSUNG SM-J510FN Build/NMF26X, SAMSUNG SM-J510MN Build/NMF26X, SAMSUNG SM-J600G Build/R16NW, SAMSUNG SM-J610G Build/M1AJQ, SAMSUNG SM-J737P Build/R16NW, SAMSUNG SM-J737T Build/R16NW, SAMSUNG SM-J810M Build/R16NW, SAMSUNG SM-N910F/N910FXXU1DQL2 Build/MMB29M, SAMSUNG SM-N950F Build/R16NW, SAMSUNG SM-N950N Build/R16NW, SAMSUNG SM-N960U Build/M1AJQ, SAMSUNG SM-P900 Build/LRX22G, SAMSUNG SM-T377W Build/NMF26X, SAMSUNG SM-T580 Build/M1AJQ, SAMSUNG SM-T820 Build/R16NW, SAMSUNG-SM-G530A, SAMSUNG-SM-G530AZ, SAMSUNG-SM-G870A Build/LRX21T, SAMSUNG-SM-G891A, SAMSUNG-SM-G891A Build/R16NW, SAMSUNG-SM-G920A, SAMSUNG-SM-G928A, SAMSUNG-SM-G930A Build/R16NW, SAMSUNG-SM-J320A, SAMSUNG-SM-J321AZ, SAMSUNG-SM-J327A, SAMSUNG-SM-J727A, SAMSUNG-SM-N915A Build/KTU84P, SAMSUNG-SM-T337A, SC-03K, SCH-I545, SGH-T999L, SGP311, SGP512, SGP621, SH-01K, SHIFT4.2, SHV39, SL729, SLA-L03, SM-A300FU, SM-A310F, SM-A320F, SM-A320FL, SM-A320FL Build/R16NW, SM-A500M, SM-A5100, SM-A510F, SM-A510M, SM-A520F, SM-A520W Build/R16NW, SM-A530F, SM-A530F Build/R16NW, SM-A530W, SM-A600FN, SM-A600T1, SM-A605GN, SM-A605GN Build/R16NW, SM-A700K, SM-A720F, SM-A730F, SM-A750G, SM-A920F, SM-C5010, SM-G316M, SM-G355M, SM-G357FZ, SM-G357M, SM-G360P, SM-G386F, SM-G530H, SM-G531H, SM-G532G, SM-G532M, SM-G532MT, SM-G550T1, SM-G570M, SM-G570M Build/R16NW, SM-G600S, SM-G610M, SM-G610M Build/M1AJQ, SM-G611F, SM-G800F, SM-G800M, SM-G850F, SM-G892U, SM-G892U Build/R16NW, SM-G900F, SM-G900F Build/NJH47F, SM-G900H, SM-G900M, SM-G900T, SM-G900T Build/LMY47X, SM-G903F, SM-G920F, SM-G920R7, SM-G925F, SM-G925P, SM-G925T, SM-G925V, SM-G928T, SM-G930F, SM-G930F Build/R16NW, SM-G930P Build/R16NW, SM-G930R4, SM-G930R4 Build/R16NW, SM-G930T Build/R16NW, SM-G930U, SM-G930U Build/R16NW, SM-G930V, SM-G930V Build/R16NW, SM-G930VC, SM-G930VL, SM-G930W8, SM-G930W8 Build/R16NW, SM-G935F, SM-G935F Build/R16NW, SM-G935P, SM-G935R4, SM-G935S, SM-G935T Build/R16NW, SM-G935V Build/R16NW, SM-G950, SM-G9500, SM-G950F, SM-G950N, SM-G950U, SM-G950U1, SM-G955N, SM-G955U, SM-G955U1, SM-G9600, SM-G960F, SM-G960N, SM-G960U, SM-G960U1, SM-G960W, SM-G9650, SM-G965F, SM-G965U, SM-G965U1, SM-J105B, SM-J106B, SM-J111M, SM-J120FN, SM-J120H, SM-J200G Build/LMY47X, SM-J200M, SM-J250F, SM-J250M, SM-J260M, SM-J320F, SM-J320FN, SM-J320M, SM-J320V, SM-J327P, SM-J327T, SM-J327T1, SM-J327U, SM-J327V, SM-J327VPP, SM-J327W, SM-J330FN, SM-J337A, SM-J337T, SM-J337V, SM-J400F, SM-J400M, SM-J400M Build/R16NW, SM-J415G, SM-J500F, SM-J500M, SM-J510H, SM-J510MN, SM-J530F, SM-J530GM, SM-J530L, SM-J600FN, SM-J600G, SM-J600G Build/R16NW, SM-J600GT, SM-J610G, SM-J700H, SM-J700M, SM-J700T, SM-J701F, SM-J701M, SM-J701MT, SM-J710F, SM-J710MN, SM-J720F, SM-J727R4, SM-J727T, SM-J727T1, SM-J727U, SM-J727V, SM-J730G, SM-J730GM, SM-J737P, SM-J737P Build/R16NW, SM-J737T, SM-J737V, SM-J810M, SM-J810M Build/R16NW, SM-J810Y, SM-N7505, SM-N900, SM-N900P, SM-N900V, SM-N900W8, SM-N910C, SM-N910T, SM-N910V, SM-N915T, SM-N9200, SM-N920C, SM-N920F, SM-N920G, SM-N920I, SM-N950F, SM-N950U, SM-N950U1, SM-N9600, SM-N9600 Build/M1AJQ, SM-N960F, SM-N960U, SM-N960U Build/M1AJQ, SM-N960U1, SM-N960W, SM-P350, SM-P555M, SM-P580, SM-P905V, SM-S337TL, SM-S367VL, SM-S727VL, SM-S737TL, SM-T110, SM-T113NU, SM-T217T, SM-T280, SM-T320, SM-T337T, SM-T350, SM-T357W, SM-T360, SM-T378V, SM-T385M, SM-T387V, SM-T530NU, SM-T560, SM-T560NU, SM-T597V, SM-T677V, SM-T700, SM-T710, SM-T713, SM-T805 Build/MMB29K, SM-T813, SM-T817V, SM-T820, SM-T827V, SM-T837V, SM-T900, SNE-LX3, SO-02H, STUDIO, Shift, Shock, Slate, T09, T1-A21w, TA-1021 Build/OPR1.170623.026, TA-1028, TA-1033, TA-1039, TA-1039 Build/OPR1.170623.026, TR10RS1, TRT-L53, TRT-LX2, TU20402-58, Tab8, Tank, TechPad_10Y, U2, U972, ULTRA, UNIQ, VF-895N, VIE-L09, VIE-L29, VK410, VKY-L09, VKY-L29, VORAGO, VS501, VS986, VS987, VS988, VS988 Build/OPR1.170623.032, VS990, VS995, VTR-L09, WAS-LX1A, WAS-LX3, XT1053, XT1562, XT1562 Build/MPDS24.107-52-11, XT1572, XT1585, XT1635-02 Build/OPNS27.76-12-22-3, XT1635-02 Build/OPNS27.76-12-22-9, XT1650 Build/OCLS27.76-69-6, Y635-L03, Z730, Z818L, Z851M, Z899VL, Z9, Z916BL, Z956, Z957, Z981, Z982, Z988, ZEI403, ZTE BLADE A0620 Build/NMF26F, ZTE BLADE A6, ZTE BLADE V8 MINI, ZTE-K88, ZTE-Z999, Zebra, a500, arc, aura, breeze, carbon_harpia, es-es, gxq6580_weg_l, hi6210sft, hi6250, hi6250 Build/MRA58K, i50F Build/NRD90M, iPhone 6plus, iris, moto e5, moto e5 Build/OPP27.91-146, moto e5 Build/OPP27.91-25, moto e5 Build/OPP27.91-72, moto e5 cruise, moto e5 play, moto e5 play Build/OCPS27.91-51-3-3, moto e5 play Build/OPG28.54-19, moto e5 play Build/OPGS28.54-19-2, moto e5 plus, moto e5 plus Build/OPP27.91-122, moto g(6), moto g(6) Build/OPS27.82-41, moto g(6) Build/OPS27.82-72, moto g(6) Build/OPS27.82-87, moto g(6) Build/OPSS27.82-87-3, moto g(6) play, moto g(6) play Build/OPP27.91-140, moto g(6) play Build/OPP27.91-143, moto g(6) play Build/OPP27.91-87, moto g(6) plus, moto g(6) plus Build/OPW27.113-89, moto g(6) plus Build/OPWS27.113-25-4, moto g(6) plus Build/OPWS27.113-89-2, moto x4, moto x4 Build/OPWS27.57-40-17, moto x4 Build/OPWS27.57-40-22, moto z3, motorola, motorola one, rv:21.0, rv:26.0, rv:27.0, rv:28.0, rv:36.0, rv:60.1.0, rv:62.0, rv:63.0, rv:64.0, rv:65.0, verykoolS5027, verykool_s5516, verykools5036, verykools5702, weimei_we]
  warnings.warn(w)
/usr/local/lib/python3.6/dist-packages/h2o/job.py:70: UserWarning: Test/Validation dataset column 'id_33' has levels not trained on: [1000x798, 1021x669, 1024x576, 1024x820, 1025x640, 1080x675, 1151x719, 1151x863, 1151x864, 1151x921, 1152x672, 1152x922, 1208x720, 1223x691, 1231x358, 1260x787, 1264x945, 1265x948, 1268x862, 1272x952, 1279x719, 1279x720, 1279x767, 1279x768, 1279x799, 1279x800, 1280x767, 1280x799, 1280x801, 1281x1024, 1281x769, 1296x810, 1344x720, 1359x767, 1360x765, 1361x768, 1364x767, 1366x766, 1366x769, 1368x912, 1399x1050, 1408x1126, 1408x1127, 1408x844, 1416x758, 1416x805, 1466x403, 1480x721, 1500x1000, 1500x840, 1501x843, 1501x844, 1536x1024, 1537x865, 1592x828, 1599x1200, 1600x1280, 1600x868, 1600x901, 1601x900, 1621x1081, 1622x1081, 1624x750, 1669x942, 1679x1050, 1679x987, 1680x1018, 1681x1050, 1720x947, 1722x1440, 1727x1079, 1767x991, 1792x768, 1792x828, 1794x1080, 1800x1200, 1800x1440, 1842x1047, 1862x1048, 1918x1078, 1918x1347, 1919x1279, 1919x1280, 1920x1017, 1920x1128, 1920x1199, 1920x1440, 1920x974, 1920x983, 1921x1200, 1926x921, 2047x1152, 2047x1279, 2048x1151, 2048x1537, 2052x1368, 2094x1080, 2112x1320, 2133x1080, 2160x1920, 2161x1080, 2162x1081, 2162x1082, 2188x1459, 2241x1080, 2241x1081, 2255x1504, 2257x1505, 2281x1081, 2303x1295, 2303x1439, 2340x1080, 2341x1080, 2341x1081, 2388x1668, 2390x1344, 2398x1599, 2399x1348, 2399x1598, 2401x1350, 2401x1351, 2462x1641, 2463x1642, 2556x1248, 2559x1079, 2559x1080, 2559x1599, 2560x1079, 2560x1313, 2560x1418, 2560x1439, 2560x1441, 2560x1599, 2561x1312, 2562x1314, 2562x1440, 2562x1441, 2592x1728, 2646x1440, 2680x1440, 2688x1242, 2696x1440, 2699x1799, 2703x1441, 2734x1824, 2735x1824, 2768x1440, 2789x1442, 2791x1440, 2880x1920, 2928x1440, 2950x1440, 2960x1442, 2999x1998, 3000x1687, 3000x1999, 3011x2007, 3120x1440, 3122x1442, 3123x1440, 3168x1980, 3199x1799, 3200x1799, 3200x1801, 3201x1799, 3239x2159, 3239x2160, 3241x2161, 3280x2048, 3439x1440, 3521x1980, 3584x2016, 3784x1584, 3839x1599, 3839x2158, 3840x1599, 3840x2159, 3840x2161, 3841x2401, 4096x2160, 4096x3072, 4225x2377, 4300x1800, 4320x2700, 4500x3001, 455x256, 4608x2592, 4800x2700, 5960x1080, 6144x3456, 683x384, 7680x4320, 792x480, 800x480, 8640x1620, 888x540, 8960x5040, 910x512, 960x480, 960x600, 993x664]
  warnings.warn(w)
/usr/local/lib/python3.6/dist-packages/h2o/job.py:70: UserWarning: Test/Validation dataset column 'id_31' has levels not trained on: [blackberry, chrome 39.0 for android, chrome 67.0 for ios, chrome 68.0, chrome 68.0 for android, chrome 68.0 for ios, chrome 69.0 for android, chrome 69.0 for ios, chrome 70.0, chrome 70.0 for android, chrome 70.0 for ios, chrome 71.0, chrome 71.0 for android, chrome 71.0 for ios, edge 18.0, firefox 61.0, firefox 62.0, firefox 63.0, firefox 64.0, firefox mobile 62.0, firefox mobile 63.0, google search application 52.0, google search application 54.0, google search application 56.0, google search application 58.0, google search application 59.0, google search application 60.0, google search application 61.0, google search application 62.0, google search application 63.0, google search application 64.0, google search application 65.0, mobile safari 12.0, opera 54.0, opera 55.0, opera 56.0, rim, safari 12.0, samsung browser 7.2, samsung browser 7.4, samsung browser 8.2, uc]
  warnings.warn(w)
/usr/local/lib/python3.6/dist-packages/h2o/job.py:70: UserWarning: Test/Validation dataset column 'id_30' has levels not trained on: [Android 9, Mac OS X 10.14, Mac OS X 10_13_6, Mac OS X 10_14, Mac OS X 10_14_0, Mac OS X 10_14_1, Mac OS X 10_14_2, iOS 12.0.0, iOS 12.0.1, iOS 12.1.0, iOS 12.1.1, iOS 12.1.2]
  warnings.warn(w)
/usr/local/lib/python3.6/dist-packages/h2o/job.py:70: UserWarning: Test/Validation dataset column 'P_emaildomain' has levels not trained on: [scranton.edu]
  warnings.warn(w)

(506691,)

In [39]:
sample_submission = pd.read_csv('/content/drive/My Drive/Credit Card Fraud Dataset/sample_submission.csv')
sample_submission.shape

(506691, 2)

In [0]:
sample_submission['isFraud'] = preds['p1'].as_data_frame().values
sample_submission.to_csv('h2o_sample_submission.csv', index=False)